# Plataforma Nilo Peçanha - Seleção de features


In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import gc # Garbage collector, para recuperar memória após carregar o data'set inicial
from sklearn.model_selection import train_test_split
from sklearn import metrics
    
%matplotlib inline

In [2]:
path = './microdados_matriculas_2020_idh.csv'

df_original = pd.read_csv(path, 
                 #nrows=5000, 
                 encoding='utf-8', 
                 sep=',')
df_original =  df_original.sample(frac=.1)
df_original.T

C:\Users\wagnermc\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3441: DtypeWarning: Columns (14) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


789051  \
Categoria da Situação                          Em curso   
Situação de Matrícula                          Em curso   
Cor / Raça                                Não declarada   
Eixo Tecnológico       Controle e Processos Industriais   
Faixa Etária                               25 a 29 anos   
Modalidade de Ensino                Educação Presencial   
Renda Familiar                            Não Declarada   
Sexo                                           Feminino   
Sub Eixo Tecnologico                          Automação   
Tipo de Curso                               Bacharelado   
Turno                                          Integral   
NomMun                               PRIMAVERA DO LESTE   
CodMunDV                                        5107040   
UF                                                   MT   
ExpectativaAnosEstudo                              9.35   
IDHM                                              0.752   
IDHM-Edu                                          0.653   

                                            339957  \
Categoria da Situação                  Concluintes   
Situação de Matrícula                    Concluída   
Cor / Raça                                  Branca   
Eixo Tecnológico                 Gestão e Negócios   
Faixa Etária                          30 a 34 anos   
Modalidade de Ensino          Educação a Distância   
Renda Familiar                        0,5<RFP<=1,0   
Sexo                                      Feminino   
Sub Eixo Tecnologico             Gestão e Negócios   
Tipo de Curso          Especialização (Lato Sensu)   
Turno                                Não se aplica   
NomMun                                 JOÃO PESSOA   
CodMunDV                                   2507507   
UF                                              PB   
ExpectativaAnosEstudo                         9.87   
IDHM                                         0.763   
IDHM-Edu                                     0.693   

                                                405635  \
Categoria da Situação                         Em curso   
Situação de Matrícula                         Em curso   
Cor / Raça                               Não declarada   
Eixo Tecnológico                     Gestão e Negócios   
Faixa Etária                              50 a 54 anos   
Modalidade de Ensino              Educação a Distância   
Renda Familiar                           Não Declarada   
Sexo                                         Masculino   
Sub Eixo Tecnologico                 Gestão e Negócios   
Tipo de Curso          Qualificação Profissional (FIC)   
Turno                                    Não se aplica   
NomMun                                       TABATINGA   
CodMunDV                                       1304062   
UF                                                  AM   
ExpectativaAnosEstudo                             8.26   
IDHM                                             0.616   
IDHM-Edu                                         0.505   

                                                     551825  \
Categoria da Situação                              Em curso   
Situação de Matrícula                              Em curso   
Cor / Raça                                            Parda   
Eixo Tecnológico       Desenvolvimento Educacional e Social   
Faixa Etária                                   35 a 39 anos   
Modalidade de Ensino                    Educação Presencial   
Renda Familiar                                   0<RFP<=0,5   
Sexo                                               Feminino   
Sub Eixo Tecnologico   Desenvolvimento Educacional e Social   
Tipo de Curso                   Especialização (Lato Sensu)   
Turno                                               Noturno   
NomMun                                           ITAPETINGA   
CodMunDV                                            2916401   
UF                                                       BA   
ExpectativaAnosEstudo  

In [3]:
#remove linhas cuja ['Cor / Raça'] = 'Não declarada'
df_original = df_original[df_original['Cor / Raça'] != 'Não declarada']

In [4]:
#remove linhas cujo ['Tipo de Curso'] = 'Ensino Fundamental I' or 'Ensino Fundamental II' or 'Educação Infantil'
tiposCurso = ['Ensino Fundamental I', 'Ensino Fundamental II', 'Educação Infantil', 'Ensino Médio', 'Mestrado Profissional', 
              'Mestrado', 'Doutorado', 'Doutorado Profissional'] 
df_original = df_original[~df_original['Tipo de Curso'].isin(tiposCurso)]

In [5]:
#mantém apenas as colunas que serão utilizadas na análise
colunas = ['Categoria da Situação', 'Cor / Raça',
       'Eixo Tecnológico', 'Faixa Etária', 'Modalidade de Ensino',
       'Renda Familiar', 'Sexo', 'Sub Eixo Tecnologico', 'Tipo de Curso',
       'Turno', 'UF', 'IDHM'] #, 'ExpectativaAnosEstudo', 'IDHM-Edu']
df = df_original[colunas]
df.T

339957  \
Categoria da Situação                  Concluintes   
Cor / Raça                                  Branca   
Eixo Tecnológico                 Gestão e Negócios   
Faixa Etária                          30 a 34 anos   
Modalidade de Ensino          Educação a Distância   
Renda Familiar                        0,5<RFP<=1,0   
Sexo                                      Feminino   
Sub Eixo Tecnologico             Gestão e Negócios   
Tipo de Curso          Especialização (Lato Sensu)   
Turno                                Não se aplica   
UF                                              PB   
IDHM                                         0.763   

                                                     551825  \
Categoria da Situação                              Em curso   
Cor / Raça                                            Parda   
Eixo Tecnológico       Desenvolvimento Educacional e Social   
Faixa Etária                                   35 a 39 anos   
Modalidade de Ensino                    Educação Presencial   
Renda Familiar                                   0<RFP<=0,5   
Sexo                                               Feminino   
Sub Eixo Tecnologico   Desenvolvimento Educacional e Social   
Tipo de Curso                   Especialização (Lato Sensu)   
Turno                                               Noturno   
UF                                                       BA   
IDHM                                                  0.667   

                                         73706   \
Categoria da Situação                  Em curso   
Cor / Raça                               Branca   
Eixo Tecnológico       Informação e Comunicação   
Faixa Etária                       30 a 34 anos   
Modalidade de Ensino        Educação Presencial   
Renda Familiar                    Não Declarada   
Sexo                                  Masculino   
Sub Eixo Tecnologico           Telecomunicações   
Tipo de Curso                        Tecnologia   
Turno                                  Integral   
UF                                           PB   
IDHM                                       0.72   

                                                     388690  \
Categoria da Situação                              Evadidos   
Cor / Raça                                            Parda   
Eixo Tecnológico       Desenvolvimento Educacional e Social   
Faixa Etária                                   25 a 29 anos   
Modalidade de Ensino                   Educação a Distância   
Renda Familiar                                Não Declarada   
Sexo                                               Feminino   
Sub Eixo Tecnologico   Desenvolvimento Educacional e Social   
Tipo de Curso                   Especialização (Lato Sensu)   
Turno                                         Não se aplica   
UF                                                       ES   
IDHM                                                    0.8   

                                                 867382  \
Categoria da Situação                          Em curso   
Cor / Raça                                        Parda   
Eixo Tecnológico       Controle e Processos Industriais   
Faixa Etária                               15 a 19 anos   
Modalidade de Ensino                Educação Presencial   
Renda Familiar                            Não Declarada   
Sexo                                           Feminino   
Sub Eixo Tecnologico                           Mecânica   
Tipo de Curso                                   Técnico   
Turno                                        Vespertino   
UF                                                   RJ   
IDHM                                              0.724   

                                                 846019               431027  \
Categoria da Situação                          Em curso             Em curso   
Cor / Raça                                        Parda                Parda   
Eixo Tecnológico       Contro

**Encoding das features**  
É feito com toda a base para evitar o erro *Found unknown categories*

In [6]:
#encoding das features
#enc = OneHotEncoder(handle_unknown='ignore').fit(X_train)
#enc = OneHotEncoder(handle_unknown='ignore', sparse=False).fit(X_train)
#enc = OrdinalEncoder().fit(X)
#enc.transform(X_train).shapea

In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder
#enc = ColumnTransformer([("encoder", OneHotEncoder(handle_unknown='ignore', sparse=True), [0,1,2])], remainder = 'passthrough').fit(X)
#enc = ColumnTransformer([("encoder", OrdinalEncoder(), list(range(1,len(df.columns)-1)))], remainder = 'passthrough').fit(df[df.columns[1:]])
enc = ColumnTransformer([("encoder", OrdinalEncoder(), list(range(0,len(df.columns)-2)))], remainder = 'passthrough').fit(df[df.columns[1:]])
print(enc.transform(df[df.columns[1:]]))

[[ 1.     3.     3.    ...  3.    14.     0.763]
 [ 3.     2.     4.    ...  2.     4.     0.667]
 [ 1.     4.     3.    ...  0.    14.     0.72 ]
 ...
 [ 1.     1.     0.    ...  1.    22.     0.739]
 [ 3.     7.     0.    ...  1.    13.     0.746]
 [ 1.     9.     1.    ...  1.     8.     0.754]]


In [8]:
#dataframe das matrículas 'concluintes' e 'evadidos'
df.query('`Categoria da Situação` != "Em curso"', inplace=True)
df.reset_index(drop=True, inplace=True)
df.T

<ipython-input-8-131747ac898d>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.query('`Categoria da Situação` != "Em curso"', inplace=True)


0      \
Categoria da Situação                  Concluintes   
Cor / Raça                                  Branca   
Eixo Tecnológico                 Gestão e Negócios   
Faixa Etária                          30 a 34 anos   
Modalidade de Ensino          Educação a Distância   
Renda Familiar                        0,5<RFP<=1,0   
Sexo                                      Feminino   
Sub Eixo Tecnologico             Gestão e Negócios   
Tipo de Curso          Especialização (Lato Sensu)   
Turno                                Não se aplica   
UF                                              PB   
IDHM                                         0.763   

                                                      1      \
Categoria da Situação                              Evadidos   
Cor / Raça                                            Parda   
Eixo Tecnológico       Desenvolvimento Educacional e Social   
Faixa Etária                                   25 a 29 anos   
Modalidade de Ensino                   Educação a Distância   
Renda Familiar                                Não Declarada   
Sexo                                               Feminino   
Sub Eixo Tecnologico   Desenvolvimento Educacional e Social   
Tipo de Curso                   Especialização (Lato Sensu)   
Turno                                         Não se aplica   
UF                                                       ES   
IDHM                                                    0.8   

                                                 2      \
Categoria da Situação                         Evadidos   
Cor / Raça                                       Parda   
Eixo Tecnológico                     Gestão e Negócios   
Faixa Etária                              15 a 19 anos   
Modalidade de Ensino               Educação Presencial   
Renda Familiar                            0,5<RFP<=1,0   
Sexo                                          Feminino   
Sub Eixo Tecnologico                 Gestão e Negócios   
Tipo de Curso          Qualificação Profissional (FIC)   
Turno                                          Noturno   
UF                                                  MG   
IDHM                                             0.751   

                                                      3      \
Categoria da Situação                           Concluintes   
Cor / Raça                                           Branca   
Eixo Tecnológico       Desenvolvimento Educacional e Social   
Faixa Etária                                   30 a 34 anos   
Modalidade de Ensino                   Educação a Distância   
Renda Familiar                                      RFP>3,5   
Sexo                                               Feminino   
Sub Eixo Tecnologico   Desenvolvimento Educacional e Social   
Tipo de Curso               Qualificação Profissional (FIC)   
Turno                                         Não se aplica   
UF                                                       RS   
IDHM                                                  0.778   

                                                 4                    5      \
Categoria da Situação                      Concluintes          Concluintes   
Cor / Raça                                      Branca                Parda   
Eixo Tecnológico              Informação e Comunicação       Infraestrutura   
Faixa Etária                              20 a 24 anos         15 a 19 anos   
Modalidade de Ensino               Educação Presencial  Educação Presencial   
Renda Familiar                            0,5<RFP<=1,0         1,0<RFP<=1,5   
Sexo                                         Masculino            Masculino   
Sub Eixo Tecnologico          Informação e Comunicação                Civil   
Tipo de Curso          Qualificação Profissional (FIC)              Técnico   
Turno                                       Vespertino             Integral   
UF                                                  SP                   RR   

In [9]:
# Separa as variáveis independentes (features = X) da variável dependente (target = y)
X = df.drop(['Categoria da Situação'], axis=1)
y = df['Categoria da Situação']

In [10]:
# Partição treino/teste (20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [11]:
X_train.shape, y_train.shape

((20031, 11), (20031,))

In [12]:
X_test.shape, y_test.shape

((5008, 11), (5008,))

In [13]:
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.feature_selection import mutual_info_classif

qtde_features = 5

**Seleção baseada em ANova (f-classif)**  
variáveis numéricas e target categórico

In [14]:
kbest = SelectKBest(f_classif, k=qtde_features).fit(enc.transform(X), y)
X_new = kbest.transform (enc.transform(X))
print(X.shape)
print(X_new.shape)

cols = kbest.get_support(indices=True)
print('Features significativas [ANova]: ' + ' | '.join(X.columns[cols]))

(25039, 11)
(25039, 5)
Features significativas [ANova]: Cor / Raça | Modalidade de Ensino | Sexo | UF | IDHM


**Seleção baseada em mutual_info_classif**  
não há dependência linerar entre as variáveis e o target

In [15]:
kbest = SelectKBest(mutual_info_classif, k=qtde_features).fit(enc.transform(X), y)
X_new = kbest.transform (enc.transform(X))
print(X.shape)
print(X_new.shape)

cols = kbest.get_support(indices=True)
print('Features significativas [mutual]: ' + ' | '.join(X.columns[cols]))

(25039, 11)
(25039, 5)
Features significativas [mutual]: Sub Eixo Tecnologico | Tipo de Curso | Turno | UF | IDHM


**Seleção baseada em chi2**  
variáveis e target categóricos

In [16]:
kbest = SelectKBest(mutual_info_classif, k=qtde_features).fit(enc.transform(X), y)
X_new = kbest.transform (enc.transform(X))
print(X.shape)
print(X_new.shape)

cols = kbest.get_support(indices=True)
print('Features significativas [chi2]: ' + ' | '.join(X.columns[cols]))

(25039, 11)
(25039, 5)
Features significativas [chi2]: Sub Eixo Tecnologico | Tipo de Curso | Turno | UF | IDHM
